[2023-05-30T15:34:15.835+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: birthday_email_dag.send_birthday_emails scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2023-05-30T15:34:15.850+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: birthday_email_dag.send_birthday_emails scheduled__2023-05-29T00:00:00+00:00 [queued]>
[2023-05-30T15:34:15.851+0000] {taskinstance.py:1308} INFO - Starting attempt 15 of 15
[2023-05-30T15:34:15.884+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): send_birthday_emails> on 2023-05-29 00:00:00+00:00
[2023-05-30T15:34:15.889+0000] {standard_task_runner.py:57} INFO - Started process 1204 to run task
[2023-05-30T15:34:15.896+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'birthday_email_dag', 'send_birthday_emails', 'scheduled__2023-05-29T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/birthday_dag.py', '--cfg-path', '/tmp/tmpkbugnvp1']
[2023-05-30T15:34:15.898+0000] {standard_task_runner.py:85} INFO - Job 220: Subtask send_birthday_emails
[2023-05-30T15:34:15.972+0000] {task_command.py:410} INFO - Running <TaskInstance: birthday_email_dag.send_birthday_emails scheduled__2023-05-29T00:00:00+00:00 [running]> on host c198daee119a
[2023-05-30T15:34:16.047+0000] {abstractoperator.py:597} ERROR - Exception rendering Jinja template for task 'send_birthday_emails', field 'op_kwargs'. Template: {'email_content': '\n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Birthday Wishes</title>\n    <style>\n        div {{\n            background-image: url(\'./birthday_image-PhotoRoom.png\');\n            width: 100%;\n            background-repeat: no-repeat;\n            height: 100vh;\n        }}\n        h1 {{\n            color: white;\n            font-size: xx-large;\n            font-weight: bold;\n            font-size: 10vh;\n            font-family: monospace;\n            position: absolute;\n            top: 30%;\n            left: 10%;\n        }}\n    </style>\n</head>\n<body>\n    <div>\n        <h1>{ employee_name }</h1>\n    </div>\n    \n</body>\n</html>\n\n'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 11, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
[2023-05-30T15:34:16.050+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 11, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
[2023-05-30T15:34:16.062+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=birthday_email_dag, task_id=send_birthday_emails, execution_date=20230529T000000, start_date=20230530T153415, end_date=20230530T153416
[2023-05-30T15:34:16.090+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 220 for task send_birthday_emails (expected token 'end of print statement', got ':'; 1204)
[2023-05-30T15:34:16.108+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-30T15:34:16.134+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
